# Generated by Django 3.2.9 on 2021-12-06 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSample',
            fields=[
                ('txn', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
