# Generated by Django 3.2.9 on 2021-12-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersample',
            name='milkshake_ordered',
            field=models.CharField(blank=True, choices=[('MANGO', 'Mango Manza'), ('STRAWBERRY', 'Strawberry Carry'), ('OREO', 'Ore-ion'), ('CHOCOLATE', 'Tsokolate')], max_length=50),
        ),
    ]
