# Generated by Django 3.2.9 on 2021-12-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database_Manager', '0002_ordersample_milkshake_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('price_per_serving', models.IntegerField()),
            ],
            options={
                'db_table': 'ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_date', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Milkshake',
            fields=[
                ('milkshake_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'milkshake',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeSize',
            fields=[
                ('recipe_size', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recipe_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('txn', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('day_date', models.DateField()),
            ],
            options={
                'db_table': 'sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('week_date', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'week',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OrderSample',
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('milkshake', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Database_Manager.milkshake')),
                ('ingredient_quantity', models.IntegerField()),
                ('price_delta', models.IntegerField()),
            ],
            options={
                'db_table': 'customization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('txn', models.OneToOneField(db_column='txn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Database_Manager.sale')),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipePrice',
            fields=[
                ('recipe_name', models.OneToOneField(db_column='recipe_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Database_Manager.recipe')),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'recipe_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('week_date', models.OneToOneField(db_column='week_date', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Database_Manager.week')),
                ('employee_role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servings',
            fields=[
                ('ingredient_name', models.OneToOneField(db_column='ingredient_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Database_Manager.ingredient')),
                ('servings', models.IntegerField()),
            ],
            options={
                'db_table': 'servings',
                'managed': False,
            },
        ),
    ]
